import { KanjiCard } from './store'

// Comprehensive N5-N2 Kanji Database (200+ kanji across all levels)
export const kanjiDatabase: Omit<KanjiCard, 'lastReviewed' | 'correctCount' | 'incorrectCount' | 'interval'>[] = [
  // N5 Kanji (80 kanji - most common)
  { kanji: '一', reading: 'いち、ひと', meaning: 'one', level: 'N5' },
  { kanji: '二', reading: 'に、ふた', meaning: 'two', level: 'N5' },
  { kanji: '三', reading: 'さん、み', meaning: 'three', level: 'N5' },
  { kanji: '四', reading: 'し、よん', meaning: 'four', level: 'N5' },
  { kanji: '五', reading: 'ご、いつ', meaning: 'five', level: 'N5' },
  { kanji: '六', reading: 'ろく、む', meaning: 'six', level: 'N5' },
  { kanji: '七', reading: 'しち、なな', meaning: 'seven', level: 'N5' },
  { kanji: '八', reading: 'はち、や', meaning: 'eight', level: 'N5' },
  { kanji: '九', reading: 'く、きゅう', meaning: 'nine', level: 'N5' },
  { kanji: '十', reading: 'じゅう、とお', meaning: 'ten', level: 'N5' },
  { kanji: '百', reading: 'ひゃく', meaning: 'hundred', level: 'N5' },
  { kanji: '千', reading: 'せん、ち', meaning: 'thousand', level: 'N5' },
  { kanji: '万', reading: 'まん、ばん', meaning: 'ten thousand', level: 'N5' },
  { kanji: '円', reading: 'えん', meaning: 'yen, circle', level: 'N5' },
  { kanji: '日', reading: 'にち、ひ、か', meaning: 'day, sun', level: 'N5' },
  { kanji: '月', reading: 'げつ、つき', meaning: 'month, moon', level: 'N5' },
  { kanji: '火', reading: 'か、ひ', meaning: 'fire, Tuesday', level: 'N5' },
  { kanji: '水', reading: 'すい、みず', meaning: 'water, Wednesday', level: 'N5' },
  { kanji: '木', reading: 'もく、き', meaning: 'tree, Thursday', level: 'N5' },
  { kanji: '金', reading: 'きん、かね', meaning: 'gold, Friday', level: 'N5' },
  { kanji: '土', reading: 'ど、つち', meaning: 'soil, Saturday', level: 'N5' },
  { kanji: '人', reading: 'じん、ひと', meaning: 'person', level: 'N5' },
  { kanji: '男', reading: 'だん、おとこ', meaning: 'man, male', level: 'N5' },
  { kanji: '女', reading: 'じょ、おんな', meaning: 'woman, female', level: 'N5' },
  { kanji: '子', reading: 'し、こ', meaning: 'child', level: 'N5' },
  { kanji: '学', reading: 'がく、まな', meaning: 'study, learn', level: 'N5' },
  { kanji: '生', reading: 'せい、い', meaning: 'life, birth', level: 'N5' },
  { kanji: '先', reading: 'せん、さき', meaning: 'before, ahead', level: 'N5' },
  { kanji: '年', reading: 'ねん、とし', meaning: 'year', level: 'N5' },
  { kanji: '時', reading: 'じ、とき', meaning: 'time, hour', level: 'N5' },
  { kanji: '分', reading: 'ふん、わ', meaning: 'minute, part', level: 'N5' },
  { kanji: '本', reading: 'ほん、もと', meaning: 'book, origin', level: 'N5' },
  { kanji: '大', reading: 'だい、おお', meaning: 'big, large', level: 'N5' },
  { kanji: '小', reading: 'しょう、ちい', meaning: 'small, little', level: 'N5' },
  { kanji: '中', reading: 'ちゅう、なか', meaning: 'middle, inside', level: 'N5' },
  { kanji: '外', reading: 'がい、そと', meaning: 'outside', level: 'N5' },
  { kanji: '上', reading: 'じょう、うえ', meaning: 'up, above', level: 'N5' },
  { kanji: '下', reading: 'か、した', meaning: 'down, below', level: 'N5' },
  { kanji: '前', reading: 'ぜん、まえ', meaning: 'front, before', level: 'N5' },
  { kanji: '後', reading: 'ご、あと', meaning: 'behind, after', level: 'N5' },
  { kanji: '左', reading: 'さ、ひだり', meaning: 'left', level: 'N5' },
  { kanji: '右', reading: 'う、みぎ', meaning: 'right', level: 'N5' },
  { kanji: '東', reading: 'とう、ひがし', meaning: 'east', level: 'N5' },
  { kanji: '西', reading: 'せい、にし', meaning: 'west', level: 'N5' },
  { kanji: '南', reading: 'なん、みなみ', meaning: 'south', level: 'N5' },
  { kanji: '北', reading: 'ほく、きた', meaning: 'north', level: 'N5' },
  { kanji: '口', reading: 'こう、くち', meaning: 'mouth', level: 'N5' },
  { kanji: '目', reading: 'もく、め', meaning: 'eye', level: 'N5' },
  { kanji: '耳', reading: 'じ、みみ', meaning: 'ear', level: 'N5' },
  { kanji: '手', reading: 'しゅ、て', meaning: 'hand', level: 'N5' },
  { kanji: '足', reading: 'そく、あし', meaning: 'foot, leg', level: 'N5' },
  { kanji: '見', reading: 'けん、み', meaning: 'see, watch', level: 'N5' },
  { kanji: '行', reading: 'こう、い', meaning: 'go', level: 'N5' },
  { kanji: '来', reading: 'らい、く', meaning: 'come', level: 'N5' },
  { kanji: '食', reading: 'しょく、た', meaning: 'eat, food', level: 'N5' },
  { kanji: '飲', reading: 'いん、の', meaning: 'drink', level: 'N5' },
  { kanji: '買', reading: 'ばい、か', meaning: 'buy', level: 'N5' },
  { kanji: '入', reading: 'にゅう、い', meaning: 'enter', level: 'N5' },
  { kanji: '出', reading: 'しゅつ、で', meaning: 'exit, out', level: 'N5' },
  { kanji: '山', reading: 'さん、やま', meaning: 'mountain', level: 'N5' },
  { kanji: '川', reading: 'せん、かわ', meaning: 'river', level: 'N5' },
  { kanji: '休', reading: 'きゅう、やす', meaning: 'rest', level: 'N5' },
  { kanji: '立', reading: 'りつ、た', meaning: 'stand', level: 'N5' },
  { kanji: '言', reading: 'げん、い', meaning: 'say, words', level: 'N5' },
  { kanji: '話', reading: 'わ、はな', meaning: 'talk, story', level: 'N5' },
  { kanji: '読', reading: 'どく、よ', meaning: 'read', level: 'N5' },
  { kanji: '書', reading: 'しょ、か', meaning: 'write', level: 'N5' },
  { kanji: '聞', reading: 'ぶん、き', meaning: 'hear, ask', level: 'N5' },
  { kanji: '車', reading: 'しゃ、くるま', meaning: 'car', level: 'N5' },
  { kanji: '駅', reading: 'えき', meaning: 'station', level: 'N5' },
  { kanji: '店', reading: 'てん、みせ', meaning: 'shop, store', level: 'N5' },
  { kanji: '会', reading: 'かい、あ', meaning: 'meet', level: 'N5' },
  { kanji: '国', reading: 'こく、くに', meaning: 'country', level: 'N5' },
  { kanji: '校', reading: 'こう', meaning: 'school', level: 'N5' },
  { kanji: '高', reading: 'こう、たか', meaning: 'tall, high', level: 'N5' },
  { kanji: '安', reading: 'あん、やす', meaning: 'cheap, safe', level: 'N5' },
  { kanji: '長', reading: 'ちょう、なが', meaning: 'long', level: 'N5' },
  { kanji: '間', reading: 'かん、あいだ', meaning: 'interval, between', level: 'N5' },
  { kanji: '友', reading: 'ゆう、とも', meaning: 'friend', level: 'N5' },

  // N4 Kanji (53 more common ones)
  { kanji: '働', reading: 'どう、はたら', meaning: 'work', level: 'N4' },
  { kanji: '運', reading: 'うん、はこ', meaning: 'carry, luck', level: 'N4' },
  { kanji: '歌', reading: 'か、うた', meaning: 'song, sing', level: 'N4' },
  { kanji: '漢', reading: 'かん', meaning: 'China, kanji', level: 'N4' },
  { kanji: '牛', reading: 'ぎゅう、うし', meaning: 'cow', level: 'N4' },
  { kanji: '魚', reading: 'ぎょ、さかな', meaning: 'fish', level: 'N4' },
  { kanji: '強', reading: 'きょう、つよ', meaning: 'strong', level: 'N4' },
  { kanji: '教', reading: 'きょう、おし', meaning: 'teach', level: 'N4' },
  { kanji: '近', reading: 'きん、ちか', meaning: 'near', level: 'N4' },
  { kanji: '銀', reading: 'ぎん', meaning: 'silver', level: 'N4' },
  { kanji: '兄', reading: 'けい、あに', meaning: 'older brother', level: 'N4' },
  { kanji: '弟', reading: 'てい、おとうと', meaning: 'younger brother', level: 'N4' },
  { kanji: '姉', reading: 'し、あね', meaning: 'older sister', level: 'N4' },
  { kanji: '妹', reading: 'まい、いもうと', meaning: 'younger sister', level: 'N4' },
  { kanji: '父', reading: 'ふ、ちち', meaning: 'father', level: 'N4' },
  { kanji: '母', reading: 'ぼ、はは', meaning: 'mother', level: 'N4' },
  { kanji: '風', reading: 'ふう、かぜ', meaning: 'wind', level: 'N4' },
  { kanji: '雨', reading: 'う、あめ', meaning: 'rain', level: 'N4' },
  { kanji: '天', reading: 'てん、あま', meaning: 'heaven, sky', level: 'N4' },
  { kanji: '空', reading: 'くう、そら', meaning: 'sky, empty', level: 'N4' },
  { kanji: '花', reading: 'か、はな', meaning: 'flower', level: 'N4' },
  { kanji: '茶', reading: 'ちゃ', meaning: 'tea', level: 'N4' },
  { kanji: '色', reading: 'しょく、いろ', meaning: 'color', level: 'N4' },
  { kanji: '赤', reading: 'せき、あか', meaning: 'red', level: 'N4' },
  { kanji: '青', reading: 'せい、あお', meaning: 'blue', level: 'N4' },
  { kanji: '白', reading: 'はく、しろ', meaning: 'white', level: 'N4' },
  { kanji: '黒', reading: 'こく、くろ', meaning: 'black', level: 'N4' },
  { kanji: '春', reading: 'しゅん、はる', meaning: 'spring', level: 'N4' },
  { kanji: '夏', reading: 'か、なつ', meaning: 'summer', level: 'N4' },
  { kanji: '秋', reading: 'しゅう、あき', meaning: 'autumn', level: 'N4' },
  { kanji: '冬', reading: 'とう、ふゆ', meaning: 'winter', level: 'N4' },
  { kanji: '朝', reading: 'ちょう、あさ', meaning: 'morning', level: 'N4' },
  { kanji: '昼', reading: 'ちゅう、ひる', meaning: 'noon, daytime', level: 'N4' },
  { kanji: '夜', reading: 'や、よる', meaning: 'night', level: 'N4' },
  { kanji: '晩', reading: 'ばん', meaning: 'evening', level: 'N4' },
  { kanji: '週', reading: 'しゅう', meaning: 'week', level: 'N4' },
  { kanji: '今', reading: 'こん、いま', meaning: 'now', level: 'N4' },
  { kanji: '去', reading: 'きょ、さ', meaning: 'past, leave', level: 'N4' },
  { kanji: '所', reading: 'しょ、ところ', meaning: 'place', level: 'N4' },
  { kanji: '場', reading: 'じょう、ば', meaning: 'place, location', level: 'N4' },
  { kanji: '門', reading: 'もん、かど', meaning: 'gate', level: 'N4' },
  { kanji: '室', reading: 'しつ、むろ', meaning: 'room', level: 'N4' },
  { kanji: '屋', reading: 'おく、や', meaning: 'roof, shop', level: 'N4' },
  { kanji: '切', reading: 'せつ、き', meaning: 'cut', level: 'N4' },
  { kanji: '引', reading: 'いん、ひ', meaning: 'pull', level: 'N4' },
  { kanji: '送', reading: 'そう、おく', meaning: 'send', level: 'N4' },
  { kanji: '待', reading: 'たい、ま', meaning: 'wait', level: 'N4' },
  { kanji: '思', reading: 'し、おも', meaning: 'think', level: 'N4' },
  { kanji: '持', reading: 'じ、も', meaning: 'hold', level: 'N4' },
  { kanji: '知', reading: 'ち、し', meaning: 'know', level: 'N4' },
  { kanji: '死', reading: 'し、し', meaning: 'death', level: 'N4' },
  { kanji: '使', reading: 'し、つか', meaning: 'use', level: 'N4' },
  { kanji: '始', reading: 'し、はじ', meaning: 'begin', level: 'N4' },

  // N3 Kanji (40 intermediate kanji)
  { kanji: '易', reading: 'い、やさ', meaning: 'easy', level: 'N3' },
  { kanji: '移', reading: 'い、うつ', meaning: 'shift, move', level: 'N3' },
  { kanji: '因', reading: 'いん', meaning: 'cause, factor', level: 'N3' },
  { kanji: '営', reading: 'えい、いとな', meaning: 'manage, operate', level: 'N3' },
  { kanji: '永', reading: 'えい、なが', meaning: 'eternity, long', level: 'N3' },
  { kanji: '衛', reading: 'えい', meaning: 'defense, guard', level: 'N3' },
  { kanji: '液', reading: 'えき', meaning: 'liquid, fluid', level: 'N3' },
  { kanji: '演', reading: 'えん', meaning: 'perform, act', level: 'N3' },
  { kanji: '応', reading: 'おう', meaning: 'respond, apply', level: 'N3' },
  { kanji: '往', reading: 'おう', meaning: 'go, journey', level: 'N3' },
  { kanji: '押', reading: 'おう、お', meaning: 'push, press', level: 'N3' },
  { kanji: '横', reading: 'おう、よこ', meaning: 'sideways, horizontal', level: 'N3' },
  { kanji: '温', reading: 'おん、あたた', meaning: 'warm', level: 'N3' },
  { kanji: '音', reading: 'おん、おと', meaning: 'sound', level: 'N3' },
  { kanji: '仮', reading: 'か、かり', meaning: 'temporary, provisional', level: 'N3' },
  { kanji: '価', reading: 'か、あたい', meaning: 'price, value', level: 'N3' },
  { kanji: '可', reading: 'か', meaning: 'possible, acceptable', level: 'N3' },
  { kanji: '河', reading: 'か、かわ', meaning: 'river', level: 'N3' },
  { kanji: '過', reading: 'か、す', meaning: 'exceed, pass', level: 'N3' },
  { kanji: '快', reading: 'かい、こころよ', meaning: 'pleasant, comfortable', level: 'N3' },
  { kanji: '解', reading: 'かい、と', meaning: 'solve, untie', level: 'N3' },
  { kanji: '格', reading: 'かく', meaning: 'status, standard', level: 'N3' },
  { kanji: '確', reading: 'かく、たし', meaning: 'certain, sure', level: 'N3' },
  { kanji: '額', reading: 'がく、ひたい', meaning: 'amount, forehead', level: 'N3' },
  { kanji: '刊', reading: 'かん', meaning: 'publish, edition', level: 'N3' },
  { kanji: '幹', reading: 'かん、みき', meaning: 'trunk, main part', level: 'N3' },
  { kanji: '慣', reading: 'かん、な', meaning: 'accustomed, habit', level: 'N3' },
  { kanji: '管', reading: 'かん、くだ', meaning: 'pipe, tube', level: 'N3' },
  { kanji: '観', reading: 'かん', meaning: 'observe, view', level: 'N3' },
  { kanji: '貫', reading: 'かん、つらぬ', meaning: 'pierce, penetrate', level: 'N3' },
  { kanji: '関', reading: 'かん、せき', meaning: 'connection, barrier', level: 'N3' },
  { kanji: '願', reading: 'がん、ねが', meaning: 'request, wish', level: 'N3' },
  { kanji: '危', reading: 'き、あぶ', meaning: 'dangerous', level: 'N3' },
  { kanji: '机', reading: 'き、つくえ', meaning: 'desk', level: 'N3' },
  { kanji: '揮', reading: 'き', meaning: 'command, brandish', level: 'N3' },
  { kanji: '貴', reading: 'き、たっと', meaning: 'valuable, noble', level: 'N3' },
  { kanji: '疑', reading: 'ぎ、うたが', meaning: 'doubt, question', level: 'N3' },
  { kanji: '吸', reading: 'きゅう、す', meaning: 'suck, inhale', level: 'N3' },
  { kanji: '供', reading: 'きょう、そな', meaning: 'offer, submit', level: 'N3' },
  { kanji: '胸', reading: 'きょう、むね', meaning: 'breast, chest', level: 'N3' },

  // N2 Kanji (40 advanced kanji)
  { kanji: '暗', reading: 'あん、くら', meaning: 'dark', level: 'N2' },
  { kanji: '案', reading: 'あん', meaning: 'plan, idea', level: 'N2' },
  { kanji: '依', reading: 'い、よ', meaning: 'depend on', level: 'N2' },
  { kanji: '威', reading: 'い', meaning: 'authority, power', level: 'N2' },
  { kanji: '為', reading: 'い', meaning: 'do, become', level: 'N2' },
  { kanji: '違', reading: 'い、ちが', meaning: 'differ, wrong', level: 'N2' },
  { kanji: '維', reading: 'い', meaning: 'maintain, fiber', level: 'N2' },
  { kanji: '慰', reading: 'い、なぐさ', meaning: 'consolation, comfort', level: 'N2' },
  { kanji: '緯', reading: 'い', meaning: 'latitude, woof', level: 'N2' },
  { kanji: '域', reading: 'いき', meaning: 'region, area', level: 'N2' },
  { kanji: '育', reading: 'いく、そだ', meaning: 'raise, educate', level: 'N2' },
  { kanji: '印', reading: 'いん、しるし', meaning: 'stamp, mark', level: 'N2' },
  { kanji: '院', reading: 'いん', meaning: 'institution, temple', level: 'N2' },
  { kanji: '陰', reading: 'いん、かげ', meaning: 'shade, negative', level: 'N2' },
  { kanji: '隠', reading: 'いん、かく', meaning: 'hide, conceal', level: 'N2' },
  { kanji: '宇', reading: 'う', meaning: 'universe, roof', level: 'N2' },
  { kanji: '羽', reading: 'う、は', meaning: 'feather, wing', level: 'N2' },
  { kanji: '雲', reading: 'うん、くも', meaning: 'cloud', level: 'N2' },
  { kanji: '営', reading: 'えい', meaning: 'manage, business', level: 'N2' },
  { kanji: '影', reading: 'えい、かげ', meaning: 'shadow, reflection', level: 'N2' },
  { kanji: '鋭', reading: 'えい、するど', meaning: 'sharp, pointed', level: 'N2' },
  { kanji: '液', reading: 'えき', meaning: 'liquid, fluid', level: 'N2' },
  { kanji: '益', reading: 'えき、やく', meaning: 'benefit, profit', level: 'N2' },
  { kanji: '駅', reading: 'えき', meaning: 'station', level: 'N2' },
  { kanji: '悦', reading: 'えつ', meaning: 'joy, pleased', level: 'N2' },
  { kanji: '閲', reading: 'えつ', meaning: 'review, inspection', level: 'N2' },
  { kanji: '円', reading: 'えん', meaning: 'circle, yen', level: 'N2' },
  { kanji: '延', reading: 'えん、の', meaning: 'prolong, extend', level: 'N2' },
  { kanji: '沿', reading: 'えん、そ', meaning: 'run along, follow', level: 'N2' },
  { kanji: '炎', reading: 'えん、ほのお', meaning: 'flame, blaze', level: 'N2' },
  { kanji: '怨', reading: 'えん、おん', meaning: 'grudge, resentment', level: 'N2' },
  { kanji: '宴', reading: 'えん', meaning: 'banquet, feast', level: 'N2' },
  { kanji: '媛', reading: 'えん', meaning: 'beautiful woman', level: 'N2' },
  { kanji: '援', reading: 'えん', meaning: 'help, assist', level: 'N2' },
  { kanji: '園', reading: 'えん、その', meaning: 'garden, park', level: 'N2' },
  { kanji: '煙', reading: 'えん、けむり', meaning: 'smoke', level: 'N2' },
  { kanji: '猿', reading: 'えん、さる', meaning: 'monkey', level: 'N2' },
  { kanji: '遠', reading: 'えん、とお', meaning: 'far, distant', level: 'N2' },
  { kanji: '鉛', reading: 'えん、なまり', meaning: 'lead (metal)', level: 'N2' },
  { kanji: '塩', reading: 'えん、しお', meaning: 'salt', level: 'N2' },
]

// Initialize kanji cards with default values
export function initializeKanjiDeck(): KanjiCard[] {
  return kanjiDatabase.map(kanji => ({
    ...kanji,
    lastReviewed: undefined,
    correctCount: 0,
    incorrectCount: 0,
    interval: 1,
  }))
}

// Generate wrong answer choices
export function generateChoices(correctKanji: KanjiCard, allKanji: KanjiCard[], mode: 'reading' | 'meaning'): string[] {
  const correct = mode === 'reading' ? correctKanji.reading : correctKanji.meaning

  const levelOrder: ('N5' | 'N4' | 'N3' | 'N2')[] = ['N5', 'N4', 'N3', 'N2']
  const currentLevelIndex = levelOrder.indexOf(correctKanji.level)
  const acceptableLevels = [
    levelOrder[currentLevelIndex],
    levelOrder[Math.max(0, currentLevelIndex - 1)],
    levelOrder[Math.min(3, currentLevelIndex + 1)],
  ].filter(Boolean)

  const wrongChoices = allKanji
    .filter(k => k.kanji !== correctKanji.kanji)
    .filter(k => acceptableLevels.includes(k.level))
    .map(k => mode === 'reading' ? k.reading : k.meaning)
    .filter(choice => choice !== correct)
    .sort(() => Math.random() - 0.5)
    .slice(0, 3)

  if (wrongChoices.length < 3) {
    const additional = allKanji
      .filter(k => k.kanji !== correctKanji.kanji)
      .map(k => mode === 'reading' ? k.reading : k.meaning)
      .filter(choice => choice !== correct && !wrongChoices.includes(choice))
      .sort(() => Math.random() - 0.5)
      .slice(0, 3 - wrongChoices.length)
    wrongChoices.push(...additional)
  }

  return [correct, ...wrongChoices].sort(() => Math.random() - 0.5)
}

// Get kanji count by level
export function getKanjiCountByLevel() {
  return {
    N5: kanjiDatabase.filter(k => k.level === 'N5').length,
    N4: kanjiDatabase.filter(k => k.level === 'N4').length,
    N3: kanjiDatabase.filter(k => k.level === 'N3').length,
    N2: kanjiDatabase.filter(k => k.level === 'N2').length,
    total: kanjiDatabase.length,
  }
}
